### ISSUE TITLE
David est décédé

### ISSUE THREAD

**Issue by Twiloo** [Matthieu-dgl/Jeu-des-Maladies#1]
C'est malheureux :(

https://github.com/Matthieu-dgl/Jeu-des-Maladies/blob/035c0608c2b6f7a43774caca6b7bea3c996d48ab/src/main/java/com/matthieudeglon/MoteursDeJeu/InitJeu.java#L61

**Comment by Matthieu-dgl** [comment]
Oui... J'aurais du mettre des noms de profs ;)
